### ISSUE TITLE
Opstart CDIO 2

### ISSUE THREAD

**Issue by AndersFrandsen** [AndersFrandsen/34_CDIO#2]
Opstartsmøde-planlægning CDIO 2
Dagsorden (gruppearbejde + uddelegering af opgaver):

- [x] - Intro til Github issues, mappe-struktur og formularer i Dropbox
- [x] - Opdatering af ordbog fra CDIO 1 (Anders)
- [x] - Risikoanalyse (Jannie + Mads)
- [x] - Kravliste, use case diagram (Anders)
- [x] - Use case beskrivelser (Nikolaj)
- [x] - Domænemodel (Jannie)
- [x] - Systemsekvensdiagram (Kasper)

Deadline er fredag kl. 16.

**Comment by Jannie2603** [comment]
Jeg har spørgsmål 
1: Mads og jeg har kigget på risikoanalysen og har også skrevet vores refleksioner omkring den i vores dokument. 
I må gerne komme med rettelser og forslag hvis der er noget I bider mærke i.

2: Jeg kan se at der er et par punkter der ikke er målbare i kravlisten. Hvad gør jeg med min viden? skal jeg sætte gule mærker og komme med spørgsmål i dokumentet eller oprette et kopi af dokumentet og sætte mærker her? eller mødes vi inden fredag og taler sammen?

**Comment by AndersFrandsen** [comment]
@Jannie2603 opret en kopi og kommenter i denne :)
