### ISSUE TITLE
Ret Dice klasse til Die

### ISSUE THREAD

**Issue by AndersFrandsen** [AndersFrandsen/34_CDIO#3]

**Comment by Hemsen** [comment]
You can't just do that!

**Comment by AndersFrandsen** [comment]
@KasperBaun hold op din spasser!

**Comment by KasperBaun** [comment]
@Jannie2603 har brug for noget expertise fra dig. Kan du hjælpe mig ?

**Comment by Jannie2603** [comment]
Jeg kigger på det @KasperBaun
