### ISSUE TITLE
Sprog: oversættelse

### ISSUE THREAD

**Issue by AndersFrandsen** [AndersFrandsen/34_CDIO#4]
Vi skal lave en dansk og engelsk version af spillet.

Sprog skal sættes i to tekst-filer (dk, en):

# FieldNames
2 = Tower
3 = Crater
osv. 

# FieldMessages
2msg = Landed on Tower
3msg = Landed on Crater
osv.

# BoardMessages
welcomeMessage = velkomsthilsen
nameInput = skriv spillerens navn
NextPlayer = Næste spillers tur
RollDice = Spiller x's tur! Slå terninger
Winner = Tillykke, spiller x har vundet
NewTurn = du er landet på 10, du får ny tur

**Comment by s176367** [comment]
Jeg har nu tilføjet 4 dokumenter i en mappe i implementering som er txt. dokumenter med beskeder og felter på både dansk og engelsk @AndersFrandsen

**Comment by AndersFrandsen** [comment]
👍 super, jeg får lige lagt dem i projektet og så lukker jeg dette issue.
